language: python
python:
  - "2.7"

notifications:
    email: false

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-sklearn
  - pip install -U pip

install:
  - travis_wait travis_retry pip install -r requirements.txt

# command to run tests
script: make test

